apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["cpu"]'
    opendatahub.io/template-display-name: vLLM CPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-xeon-runtime
    openshift.io/display-name: llama32-3b-cpu
  name: llama32-3b-cpu
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=llama3_json'
        - '--chat-template=/app/data/template/tool_chat_template_llama3.2_json.jinja'
        - '--block-size=128'
        - '--dtype=bfloat16'
        - '--max-model-len=8192'
        - '--distributed-executor-backend=mp'
        - '--max-num-batched-tokens=2048'
        - '--max-num-seqs=256'
        - '--tensor-parallel-size=1'
        - '--pipeline-parallel-size=1'
      command:
        - vllm
        - serve
      env:
        - name: HF_HOME
          value: "/tmp/hf_home"
        # jemalloc memory allocator not supported on this image, using libomp instead
        - name: LD_PRELOAD
          value: "/usr/lib64/libomp.so"
      image: 'registry.redhat.io/rhaii/vllm-cpu-rhel9:3.4.0'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /app/data/template/tool_chat_template_llama3.2_json.jinja
          name: chat-template-volume
          subPath: tool_chat_template_llama3.2_json.jinja
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 4Gi
      name: shm
    - name: chat-template-volume
      configMap:
        name: chat-template
